# Generated by Django 4.2.5 on 2023-11-15 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True)),
                ('country', models.CharField(blank=True, choices=[('CANADA', 'CANADA'), ('USA', 'USA'), ('UK', 'UK'), ('GERMANY', 'GERMANY'), ('FRANCE', 'FRANCE'), ('OTHER', 'OTHER'), ('RUSSIA', 'RUSSIA'), ('VIETNAM', 'VIETNAME'), ('CHINA', 'CHINA')], max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
