# Generated by Django 4.2.5 on 2023-11-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='casts',
            field=models.ManyToManyField(related_name='acted_in_movies', to='Movie.cast'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(related_name='movies_in_genre', to='Movie.genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='production_companies',
            field=models.ManyToManyField(related_name='movies_producted_by', to='Movie.production_company'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='production_countries',
            field=models.ManyToManyField(related_name='movies_in_country', to='Movie.production_country'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='spoken_languages',
            field=models.ManyToManyField(related_name='spoken_in_movies', to='Movie.spoken_language'),
        ),
    ]
