# Generated by Django 4.2.5 on 2023-11-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0010_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_rating',
            name='rating_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user_rating',
            name='rating_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='view_history',
            name='view_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
