# Generated by Django 4.2.5 on 2023-11-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0011_alter_user_rating_rating_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_rating',
            name='rating_score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
