# Generated by Django 4.2.5 on 2023-11-21 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0012_alter_user_rating_rating_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='popularity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='rating_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='view_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
