# Generated by Django 4.2.5 on 2024-03-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0013_movie_popularity_movie_rating_score_movie_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='cast',
            name='gender',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='production_company',
            name='logo_path',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='production_company',
            name='origin_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='production_country',
            name='iso_3166_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='spoken_language',
            name='english_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='spoken_language',
            name='iso_639_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
