# Generated by Django 4.2.5 on 2024-03-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0014_cast_gender_production_company_logo_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='casts',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='production_companies',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='production_countries',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='spoken_languages',
        ),
        migrations.AlterField(
            model_name='cast',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='production_company',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='production_country',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='spoken_language',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
