# Generated by Django 4.2.5 on 2024-03-02 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0015_remove_movie_casts_remove_movie_genres_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_rating',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='user_rating',
            name='user',
        ),
        migrations.RemoveField(
            model_name='view_history',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='view_history',
            name='user',
        ),
    ]
