# Generated by Django 4.2.5 on 2024-03-02 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0018_alter_cast_id_alter_movie_vote_average'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='casts',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='production_companies',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='production_countries',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='spoken_languages',
        ),
        migrations.RemoveField(
            model_name='user_rating',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='user_rating',
            name='user',
        ),
        migrations.RemoveField(
            model_name='view_history',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='view_history',
            name='user',
        ),
    ]
