# Generated by Django 4.2.5 on 2024-03-02 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Movie', '0019_remove_movie_casts_remove_movie_genres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='casts',
            field=models.ManyToManyField(related_name='acted_in_movies', to='Movie.cast'),
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(related_name='movies_in_genre', to='Movie.genre'),
        ),
        migrations.AddField(
            model_name='movie',
            name='production_companies',
            field=models.ManyToManyField(related_name='movies_producted_by', to='Movie.production_company'),
        ),
        migrations.AddField(
            model_name='movie',
            name='production_countries',
            field=models.ManyToManyField(related_name='movies_in_country', to='Movie.production_country'),
        ),
        migrations.AddField(
            model_name='movie',
            name='spoken_languages',
            field=models.ManyToManyField(related_name='spoken_in_movies', to='Movie.spoken_language'),
        ),
        migrations.AddField(
            model_name='user_rating',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Movie.movie'),
        ),
        migrations.AddField(
            model_name='user_rating',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='view_history',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Movie.movie'),
        ),
        migrations.AddField(
            model_name='view_history',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
