# Generated by Django 4.2.5 on 2024-03-03 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0023_alter_cast_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cast',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
