# Generated by Django 4.2.5 on 2023-11-17 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_remove_movie_actors_remove_movie_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_rating',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='user_rating',
            name='user',
        ),
        migrations.RemoveField(
            model_name='view_history',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='view_history',
            name='user',
        ),
    ]
