# Generated by Django 4.2.5 on 2023-11-17 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_remove_user_rating_movie_remove_user_rating_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='actor',
        ),
        migrations.DeleteModel(
            name='country',
        ),
        migrations.DeleteModel(
            name='genre',
        ),
        migrations.DeleteModel(
            name='movie',
        ),
        migrations.DeleteModel(
            name='user_rating',
        ),
        migrations.DeleteModel(
            name='view_history',
        ),
    ]
