# Generated by Django 4.2.5 on 2023-11-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cast',
            new_name='Actor',
        ),
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(related_name='acted_in_movies', to='movie.actor'),
        ),
    ]
